print('Hello Friend! Whats your name?')
Name=input('Name: ')
print(Name, 'Thats a nice name. I wish I had one....')
print('HEY! Ive got an idea! Why dont you give me a name?')
CompName=input('What would you like to call me: ')
print(CompName, 'sounds like a cool name.')
print('What is your favorite number?')
Number=input('Number: ')
print('I like', Number, 'Too!')
#print('What do you think about math?')
#print('[Input] If you like math, input 1. If not, input 2.')
#Math=input('Math: ')
#if(Math.__contains__('1')):
#  print('Good for you! Im not good at math.')
#elif(Math.__contains__('2')):
#  print('Same here! Im just not good at math XD.')
print('Well it was nice to meet you', Name, 'I hope we meet again soon')